export const GET_SEARCH_AUTHOR = 'GET_SEARCH_AUTHOR';
export const GET_SEARCH_AUTHOR_SUCCESS = 'GET_SEARCH_AUTHOR_SUCCESS';
export const GET_SEARCH_AUTHOR_FAIL = 'GET_SEARCH_AUTHOR_FAIL';

export const GET_SEARCH_WORK = 'GET_SEARCH_WORK';
export const GET_SEARCH_WORK_SUCCESS = 'GET_SEARCH_WORK_SUCCESS';
export const GET_SEARCH_WORK_FAIL = 'GET_SEARCH_WORK_FAIL';

export const CHANGE_SEARCH_TAB = 'CHANGE_SEARCH_TAB';
export const SET_SEARCH_WORD = 'SET_SEARCH_WORD';
export const SET_SEARCH_SORT = 'SET_SEARCH_SORT';
export const SET_HEADER_VISIBLE = 'SET_HEADER_VISIBLE';
export const SET_FOOTER_VISIBLE = 'SET_FOOTER_VISIBLE';

export const POST_WORKPLACE_MY = 'POST_WORKPLACE_MY';
export const POST_WORKPLACE_MY_SUCCESS = 'POST_WORKPLACE_MY_SUCCESS';
export const POST_WORKPLACE_MY_FAIL = 'POST_WORKPLACE_MY_FAIL';

export const POST_WORKPLACE = 'POST_WORKPLACE';
export const POST_WORKPLACE_SUCCESS = 'POST_WORKPLACE_SUCCESS';
export const POST_WORKPLACE_FAIL = 'POST_WORKPLACE_FAIL';

export const GET_WORK = 'GET_WORK';
export const GET_WORK_SUCCESS = 'GET_WORK_SUCCESS';
export const GET_WORK_FAIL = 'GET_WORK_FAIL';