export const GET_SEARCH_AUTHOR = 'GET_SEARCH_AUTHOR';
export const GET_SEARCH_AUTHOR_SUCCESS = 'GET_SEARCH_AUTHOR_SUCCESS';
export const GET_SEARCH_AUTHOR_FAIL = 'GET_SEARCH_AUTHOR_FAIL';

export const GET_SEARCH_WORK = 'GET_SEARCH_WORK';
export const GET_SEARCH_WORK_SUCCESS = 'GET_SEARCH_WORK_SUCCESS';
export const GET_SEARCH_WORK_FAIL = 'GET_SEARCH_WORK_FAIL';

export const CHANGE_SEARCH_TAB = 'CHANGE_SEARCH_TAB';
export const SET_SEARCH_WORD = 'SET_SEARCH_WORD';
export const SET_SEARCH_SORT = 'SET_SEARCH_SORT';